name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  API_URL: ${{ secrets.API_URL }}
  TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
  TRELLO_KEY: ${{ secrets.TRELLO_KEY }}

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
      #run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      #run: npx playwright test
      #run: npx playwright test --config=config/playwright.config.ts --grep-invert @log_in
      run: npx playwright test --config=config/playwright.config.ts --grep @smoke
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
